# Action to build a release build on a specific tag
name: Build Tagged Release
on:
  workflow_dispatch:
  push:
    tags: '*'
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.75.0
          target: i686-pc-windows-msvc
      - name: Build Client
        run: cargo build --release --verbose --target i686-pc-windows-msvc
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ASI Plugin
          path: "./target/i686-pc-windows-msvc/release/pocket_relay_plugin.dll"
