name: Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Client
        run: cargo build --verbose --target i686-pc-windows-msvc
      - name: Run tests
        run: cargo test --verbose --target i686-pc-windows-msvc
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ASI Plugin
          path: "./target/i686-pc-windows-msvc/debug/pocket_relay_plugin.dll"
